/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_norman_ffmpegguide_NativeUtil */

#ifndef _Included_com_norman_ffmpegguide_NativeUtil
#define _Included_com_norman_ffmpegguide_NativeUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_norman_ffmpegguide_NativeUtil
 * Method:    hello
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_norman_ffmpegguide_NativeUtil_hello
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
